import Head from 'next/head'
import { useState } from 'react';
import { motion } from "framer-motion"
import { useForm } from "react-hook-form";

import Tabs from '../components/Tabs'
import Cards from '../components/Cards'

export default function Home() {

  const [movies, setMovies] = useState([]);



  const { register, handleSubmit, reset, formState: { errors } } = useForm();

  const onSubmit = (data) => {
    console.log(data);
    let cnt = localStorage.getItem('count');
    console.log(cnt);
    cnt = cnt == undefined ? 0 : cnt;
    cnt++;
    localStorage.setItem('count', cnt.toString());
    localStorage.setItem(cnt.toString(), JSON.stringify(data));
    reset();
  }


  return (
    <div >
      <Head>
        <title>IMDB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=' overflow-hidden flex flex-row min-h-screen text-white'>
        <div className=' bg-gray-900 w-3/5 p-2'>
          <div className='flex flex-col items-center'>
            <h1 className=' mt-10 text-4xl font-sans font-bold text-gradient
            bg-gradient-to-r from-cyan-500 via-indigo-600 to-green-500 '>Movies For You !!</h1>
            <hr className=' w-64 ml-8 h-2 rounded-xl bg-gradient-to-r from-green-500 to-sky-500 border-none' />
          </div>
          <Tabs>
            <div label='English'>
              <Cards lang='English' />
            </div>

            <div label='Hindi'>
              <Cards lang="Hindi" />
            </div>

            <div label='Marathi'>
              <Cards lang="Marathi" />
            </div>

            <div label='Tamil'>
              <Cards lang="Tamil" />
            </div>

          </Tabs>
        </div>


        {/* Add A Movie */}
        <motion.div

          initial={{ x: 100, opacity: 0 }}
          animate={{ x: 0, opacity: 1 }}
          transition={{ duration: 0.7, type: "tween" }}
          className=' overflow-hidden flex flex-col bg-gray-800 w-2/5 py-8'>
          <h1 className=' mx-auto font-bold font-mono text-xl'>Add a Movie</h1>
          <div className=' px-4'>

            <form onSubmit={handleSubmit(onSubmit)} >
              <div className="mb-6 mt-10">
                <label htmlFor="title" className="block mb-2 text-sm font-medium">Title</label>
                <input
                  {...register("title", { required: true })}
                  type="text" id="title" className="shadow-sm bg-gray-50 text-gray-900 
                  text-sm rounded-lg ring-4 focus:ring-cyan-500 focus:border-cyan-500 block w-full p-2.5 "></input>
              </div>
              <div className="mb-6">
                <label htmlFor="description" className="block mb-2 text-sm font-medium">Description</label>
                <textarea
                  {...register("description", { required: true })}
                  id="description" className="shadow-sm bg-gray-50 border text-gray-900 text-sm rounded-lg ring-2 focus:ring-cyan-500 focus:border-cyan-500 block w-full p-2.5 " required></textarea>
              </div>
              <div className="mb-6">
                <h1 className=' text-lg mb-5'>Image</h1>
                <label htmlFor="image" className="block mb-2 text-sm font-medium">URL</label>
                <input
                  {...register("image")}
                  type="text" id="image" className="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg 
                  ring-2 focus:ring-cyan-500 focus:border-cyan-500 block w-full p-2.5 "></input>
                <p className='my-2'>or</p>
                <input
                  {...register("image")}
                  type="file" />
              </div>
              {/* rating system */}
              <div className="flex items-center space-x-1 mb-6 mt-10 w-56 label-design">
                <span className="text-md font-medium ">Rating : </span>
                <div className="rating inline">

                  <input {...register('rate', { required: true })} value={5} type="radio" className='rate' name='rate' id="star5" />
                  <label htmlFor="star5"></label>

                  <input {...register('rate', { required: true })} value={4} type="radio" className='rate' name='rate' id="star4" />
                  <label htmlFor="star4"></label>

                  <input {...register('rate', { required: true })} value={3} type="radio" className='rate' name='rate' id="star3" />
                  <label htmlFor="star3"></label>

                  <input {...register('rate', { required: true })} value={2} type="radio" className='rate' name='rate' id="star2" />
                  <label htmlFor="star2"></label>

                  <input {...register('rate', { required: true })} value={1} type="radio" className='rate' name='rate' id="star1" />
                  <label htmlFor="star1"></label>

                </div>
              </div>

              <label className='text-lg' htmlFor="lang">Language : </label>
              <select {...register('lang', { required: true })} className='w-44 h-8 text-lg text-center font-semibold bg-gray-400 ring-2 ring-cyan-400 rounded-lg mb-8' name="lang" id="lang">
                <option value="English">English</option>
                <option value="Hindi">Hindi</option>
                <option value="Tamil">Tamil</option>
                <option value="Marathi">Marathi</option>
              </select>
              <button type="submit" className="text-black text-lg block font-semibold font-sans bg-rose-500 hover:bg-rose-400 focus:ring-4 focus:outline-none focus:ring-blue-300 rounded-lg px-5 py-2.5 text-center">Register new account</button>
            </form>

          </div>
        </motion.div>
      </main >

    </div >
  )
}
